name: ci
on: push

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Start static server
        run: |
          npx --yes http-server -p 4173 -c-1 . &>/dev/null &
          echo "SERVER_PID=$!" >> $GITHUB_ENV
          sleep 2

      - name: Smoke test (index.html has title)
        run: |
          curl -sSf http://localhost:4173/index.html | grep -q "筋トレメモ"

      - name: Stop server
        if: always()
        run: kill $SERVER_PID