# .github/workflows/ci.yml
name: ci
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check index.html exists
        run: |
          test -f index.html || (echo "index.html not found"; exit 1)
      - name: Print first line
        run: head -n 1 index.html || true