name: ci
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: |
          npm ci || npm i --no-audit --no-fund

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Lint
        run: npm run lint || echo "lint skipped (no config)"

      - name: Unit tests
        run: npm test || echo "no unit tests yet"

      - name: E2E (serve + basic smoke)
        run: |
          npx http-server -p 4173 -c-1 . > /dev/null 2>&1 &
          npx wait-on http://127.0.0.1:4173/index.html
          node -e "const f=require('node-fetch');"
          npx playwright test
